#!/usr/bin/env python3
"""
Financial Deal Comparison Tool
==============================
Compares two deals using REPORTED (unadjusted) EBITDA only.

Deal 1: Virgin Music Group / Downtown Music Holdings ($775M)
Deal 2: Playlist + EGYM Merger ($7.5B EV, $785M new equity)

All data sourced from publicly available URLs cited inline.

Author: Generated by Claude
Date: March 2026
"""

from dataclasses import dataclass, field
from typing import Optional

try:
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    import numpy as np
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False

try:
    from colorama import init, Fore, Style
    init(autoreset=True)
    C = {
        "header":   Style.BRIGHT + Fore.CYAN,
        "sep":      Fore.BLUE,
        "deal":     Style.BRIGHT + Fore.YELLOW,
        "label":    Fore.WHITE,
        "value":    Style.BRIGHT + Fore.WHITE,
        "money":    Style.BRIGHT + Fore.GREEN,
        "multiple": Style.BRIGHT + Fore.CYAN,
        "warn":     Style.BRIGHT + Fore.RED,
        "caution":  Fore.YELLOW,
        "risk":     Fore.RED,
        "na":       Style.DIM + Fore.WHITE,
        "key_obs":  Style.BRIGHT + Fore.YELLOW,
        "dim":      Style.DIM,
        "reset":    Style.RESET_ALL,
    }
except ImportError:
    C = {k: "" for k in ["header","sep","deal","label","value","money","multiple",
                          "warn","caution","risk","na","key_obs","dim","reset"]}


# =============================================================================
# DATA SOURCES — every number is traceable to a URL
# =============================================================================

SOURCES = {
    "downtown_financials": {
        "url": "https://www.billboard.com/pro/downtown-music-holdings-sale-board-exploring/",
        "description": "Billboard: Downtown's $900M gross revenue, $130M net revenue, ~$40M EBITDA (3 sources)",
        "accessed": "2024-07-12",
    },
    "downtown_deal_press_release": {
        "url": "https://www.prnewswire.com/news-releases/virgin-music-group-completes-acquisition-of-downtown-302693634.html",
        "description": "PRNewswire: VMG completes $775M Downtown acquisition, Feb 20 2026",
        "accessed": "2026-02-20",
    },
    "downtown_eu_approval": {
        "url": "https://imusician.pro/en/resources/blog/virgin-music-completes-downtown-acquisition",
        "description": "iMusician: EC approval conditioned on Curve divestiture",
        "accessed": "2026-02-13",
    },
    "downtown_mbw_analysis": {
        "url": "https://www.musicbusinessworldwide.com/4-observations-on-downtowns-775-million-sale-to-universal-music-group-virgin-music-group/",
        "description": "MBW: Downtown financial analysis — $900M gross, $130M net, ~$40M EBITDA, agency model",
        "accessed": "2025-01-12",
    },
    "downtown_variety": {
        "url": "https://variety.com/2026/music/news/universal-virgin-music-complete-775-million-acquisition-downtown-1236668336/",
        "description": "Variety: Deal completion details, CD Baby + FUGA + Songtrust assets",
        "accessed": "2026-02-20",
    },
    "playlist_egym_press_release": {
        "url": "https://www.prnewswire.com/news-releases/playlist-and-egym-announce-agreement-to-merge-and-785-million-in-new-equity-investments-bringing-together-global-leaders-in-fitness-and-wellness-technology-302662191.html",
        "description": "PRNewswire: Playlist/EGYM merger, $7.5B EV, $785M new equity, >$800M combined net revenue",
        "accessed": "2026-01-15",
    },
    "playlist_egym_egym_page": {
        "url": "https://us.egym.com/en-us/playlist-egym-announce-merger",
        "description": "EGYM: Merger details, $800M+ combined net revenue, 'strong profitability'",
        "accessed": "2026-01-15",
    },
    "playlist_egym_athletech": {
        "url": "https://athletechnews.com/classpass-mindbody-playlist-egym-merger-7-5-billion-deal/",
        "description": "Athletech News: Deal context, IPO consideration in 2024, Playlist rebranding",
        "accessed": "2026-01-15",
    },
    "playlist_egym_munich_startup": {
        "url": "https://www.munich-startup.de/en/116314/egym-and-playlist-join-forces/",
        "description": "Munich Startup: EGYM valued at ~$2.5B within deal per Handelsblatt",
        "accessed": "2026-01-21",
    },
    "playlist_egym_kirkland": {
        "url": "https://www.kirkland.com/news/press-release/2026/01/kirkland-advises-playlist-in-merger-with-egym",
        "description": "Kirkland & Ellis: Legal advisor confirmation, $7.5B EV",
        "accessed": "2026-01-15",
    },
    "playlist_zoominfo": {
        "url": "https://www.zoominfo.com/c/mindbody-inc/113934961",
        "description": "ZoomInfo: Mindbody ClassPass revenue ~$364.7M (pre-merger Playlist standalone estimate)",
        "accessed": "2026-03",
    },
    "music_catalog_multiples": {
        "url": "https://www.billboard.com/pro/music-catalog-market-attractive-slower-growth-shot-tower/",
        "description": "Billboard/Shot Tower: Music publishing multiples 16.1x NPS in 2024",
        "accessed": "2025-04-02",
    },
    "hipgnosis_deal": {
        "url": "https://www.musicbusinessworldwide.com/the-biggest-music-business-deals-of-2024-from-irving-azoff-to-daddy-yankee-hipgnosis-and-queen/",
        "description": "MBW: Hipgnosis $1.6B (Blackstone), Sony/Queen $1.27B, BMI ~$1.4B",
        "accessed": "2024-12-04",
    },
}


# =============================================================================
# DEAL DATA STRUCTURES
# =============================================================================

@dataclass
class SynergyProfile:
    cost_synergies_mm: Optional[float] = None
    cost_synergies_note: str = ""
    revenue_synergies_mm: Optional[float] = None
    revenue_synergies_note: str = ""
    revenue_synergy_inflation: str = "UNKNOWN"  # LOW / MODERATE / HIGH


@dataclass
class IntegrationCosts:
    total_mm: Optional[float] = None
    note: str = ""


@dataclass
class FinancialWording:
    """Captures specific financial language used in deal communications and what it signals."""
    term: str
    used_in: str          # Where this term appeared (press release, analyst note, etc.)
    literal_meaning: str  # What the term technically means
    subtext: str          # What the term is often used to obscure or signal
    red_flag: bool = False


@dataclass
class ComparableTransaction:
    name: str
    year: int
    ev_revenue: Optional[float] = None
    ev_ebitda: Optional[float] = None
    note: str = ""


@dataclass
class Deal:
    name: str
    acquirer: str
    target: str
    sector: str
    announced: str
    closed: str
    deal_value_mm: float
    enterprise_value_mm: float
    consideration: str

    # Revenue
    revenue_mm: float
    revenue_label: str
    alt_revenue_mm: Optional[float] = None
    alt_revenue_label: str = ""

    # EBITDA — REPORTED ONLY (not adjusted)
    reported_ebitda_mm: Optional[float] = None
    ebitda_source_note: str = ""
    ebitda_definition_warning: str = ""

    # Adjusted EBITDA (shown for disclosure but NOT used in analysis)
    adjusted_ebitda_mm: Optional[float] = None
    adjusted_ebitda_note: str = ""

    # Net Income
    net_income_mm: Optional[float] = None

    # Computed multiples
    synergies: SynergyProfile = field(default_factory=SynergyProfile)
    integration_costs: IntegrationCosts = field(default_factory=IntegrationCosts)
    comparable_transactions: list = field(default_factory=list)
    risks: list = field(default_factory=list)
    key_sources: list = field(default_factory=list)
    financial_wording: list = field(default_factory=list)

    @property
    def ev_revenue(self) -> Optional[float]:
        if self.revenue_mm and self.revenue_mm > 0:
            return self.enterprise_value_mm / self.revenue_mm
        return None

    @property
    def ev_alt_revenue(self) -> Optional[float]:
        if self.alt_revenue_mm and self.alt_revenue_mm > 0:
            return self.enterprise_value_mm / self.alt_revenue_mm
        return None

    @property
    def ev_reported_ebitda(self) -> Optional[float]:
        if self.reported_ebitda_mm and self.reported_ebitda_mm > 0:
            return self.enterprise_value_mm / self.reported_ebitda_mm
        return None

    @property
    def reported_ebitda_margin(self) -> Optional[float]:
        if self.reported_ebitda_mm and self.revenue_mm and self.revenue_mm > 0:
            return (self.reported_ebitda_mm / self.revenue_mm) * 100
        return None


# =============================================================================
# DEAL DEFINITIONS
# =============================================================================

downtown = Deal(
    name="Virgin Music Group / Downtown Music Holdings",
    acquirer="Virgin Music Group (Universal Music Group subsidiary)",
    target="Downtown Music Holdings LLC",
    sector="Music Services / Distribution / Publishing",
    announced="December 2024",
    closed="February 20, 2026",
    deal_value_mm=775,
    enterprise_value_mm=775,  # All-cash, no debt assumption disclosed
    consideration="All-cash ($775M)",

    revenue_mm=130,
    revenue_label="Net Revenue (fees retained after paying rights holders) — agency accounting model",
    alt_revenue_mm=900,
    alt_revenue_label="Gross Revenue (total throughput incl. pass-through royalties to rights holders)",

    reported_ebitda_mm=40,
    ebitda_source_note=(
        "Per Billboard (3 anonymous sources familiar with financials). "
        "Downtown is private — no SEC filings. This is the only EBITDA figure available. "
        "The exact definition is UNKNOWN. It may or may not exclude stock comp and one-time items. "
        "Source: https://www.billboard.com/pro/downtown-music-holdings-sale-board-exploring/"
    ),
    ebitda_definition_warning=(
        "CAUTION: Downtown is a private company using an agency accounting model. "
        "The $40M EBITDA figure is sourced from anonymous parties and cannot be independently verified. "
        "We do NOT know if this is truly 'reported' or already adjusted. Treat as approximate."
    ),

    adjusted_ebitda_mm=None,
    adjusted_ebitda_note="No separate adjusted figure disclosed (private company).",

    net_income_mm=None,

    synergies=SynergyProfile(
        cost_synergies_mm=None,
        cost_synergies_note=(
            "Not disclosed. EU required divestiture of Curve (royalty accounting platform), "
            "removing a key technology asset. VMG says Downtown brands (CD Baby, FUGA, Songtrust) "
            "will be preserved."
        ),
        revenue_synergies_mm=None,
        revenue_synergies_note=(
            "Qualitative only. UMG gains indie distribution market share: 5,000+ B2B clients, "
            "4M+ creators, 145 countries. Cross-sell into UMG global infrastructure. "
            "No dollar figures. The entire deal premium is effectively an unquantified revenue synergy. "
            "Source: https://www.prnewswire.com/news-releases/virgin-music-group-completes-acquisition-of-downtown-302693634.html"
        ),
        revenue_synergy_inflation="MODERATE",
    ),

    integration_costs=IntegrationCosts(
        total_mm=None,
        note=(
            "Not disclosed. Curve divestiture is a mandated cost/friction. "
            "Founder Justin Kalifowitz exiting. Pieter van Rijn (ex-Downtown CEO) named VMG COO. "
            "Source: https://variety.com/2026/music/news/universal-virgin-music-complete-775-million-acquisition-downtown-1236668336/"
        ),
    ),

    comparable_transactions=[
        ComparableTransaction("Blackstone / Hipgnosis Songs Fund", 2024, ev_ebitda=19.0,
                              note="Music catalog; ~18-20x estimated EBITDA"),
        ComparableTransaction("New Mountain / BMI", 2024, note="~$1.4B; multiples not disclosed"),
        ComparableTransaction("Sony / Queen catalog", 2024, note="$1.27B; ~25x NPS"),
        ComparableTransaction("Concord / Round Hill", 2023, note="$469M; ~16x NPS"),
    ],

    risks=[
        "19.4x EBITDA on $40M for a services business (not a catalog) — services normally trade 8-12x",
        "CD Baby (2M+ DIY creators) may conflict with UMG CEO Grainge's skepticism of DIY distribution",
        "EU forced Curve divestiture — lost technology asset",
        "Agency accounting: $900M gross revenue is mostly pass-through; real economics are $130M net",
        "Independent music community opposition (IMPALA) may cause client attrition",
        "Low-margin, high-competition space — DistroKid, TuneCore, Believe all competing",
    ],

    key_sources=[
        "downtown_financials", "downtown_deal_press_release", "downtown_eu_approval",
        "downtown_mbw_analysis", "downtown_variety",
    ],
)

playlist_egym = Deal(
    name="Playlist + EGYM Merger",
    acquirer="Playlist (Vista Equity Partners portfolio co) + new investors (Affinity Partners)",
    target="EGYM GmbH (Munich) merging into Playlist (parent of Mindbody, ClassPass, Booker)",
    sector="Fitness & Wellness Technology / SaaS / Connected Hardware / Corporate Wellness",
    announced="January 15, 2026",
    closed="Pending regulatory approval (expected 2026)",
    deal_value_mm=785,   # New equity investment amount
    enterprise_value_mm=7500,  # Combined enterprise value
    consideration=(
        "$785M in new equity led by Affinity Partners, Vista, Temasek, L Catterton. "
        "EGYM becomes subsidiary of Playlist. Not a traditional acquisition — "
        "this is a merger with fresh capital injection, not a buyout."
    ),

    revenue_mm=800,
    revenue_label=(
        "Combined net revenue (Playlist + EGYM, 2025). "
        "Playlist standalone estimated ~$365-450M (ZoomInfo: $364.7M for Mindbody-ClassPass). "
        "EGYM standalone estimated ~$350-435M (implied from combined minus Playlist). "
        "Source: https://us.egym.com/en-us/playlist-egym-announce-merger"
    ),

    reported_ebitda_mm=None,
    ebitda_source_note=(
        "NOT DISCLOSED. Both Playlist (private, Vista portfolio) and EGYM (private, Munich) "
        "do not report EBITDA publicly. The press release says 'strong profitability' but "
        "provides no figures. We cannot compute EV/EBITDA for this deal. "
        "Source: https://www.prnewswire.com/news-releases/playlist-and-egym-announce-agreement-to-merge-and-785-million-in-new-equity-investments-bringing-together-global-leaders-in-fitness-and-wellness-technology-302662191.html"
    ),
    ebitda_definition_warning=(
        "NO EBITDA AVAILABLE. 'Strong profitability' is the only statement from the companies. "
        "Without actual EBITDA figures, the EV/EBITDA multiple cannot be calculated. "
        "This is a material gap in the analysis."
    ),

    adjusted_ebitda_mm=None,
    adjusted_ebitda_note="Not disclosed.",

    net_income_mm=None,

    synergies=SynergyProfile(
        cost_synergies_mm=None,
        cost_synergies_note=(
            "Not disclosed. Both companies will continue operating their existing brands. "
            "Playlist brands (Mindbody, ClassPass, Booker) continue as-is; EGYM becomes subsidiary."
        ),
        revenue_synergies_mm=None,
        revenue_synergies_note=(
            "Geographic cross-expansion is the core thesis: EGYM enters North America/Asia via Playlist; "
            "Playlist enters Europe via EGYM. Corporate wellness cross-sell (EGYM Wellpass to Playlist's "
            "studio network). AI/personalization investment. No dollar figures. "
            "Source: https://us.egym.com/en-us/playlist-egym-announce-merger"
        ),
        revenue_synergy_inflation="MODERATE",
    ),

    integration_costs=IntegrationCosts(
        total_mm=None,
        note=(
            "Not disclosed. Brands preserved, leadership merged (dual co-founders). "
            "Integration complexity: software (Mindbody SaaS) + hardware (EGYM smart equipment) "
            "+ consumer marketplace (ClassPass) + corporate wellness (Wellpass). "
            "Four different business models under one roof."
        ),
    ),

    comparable_transactions=[
        ComparableTransaction("Vista / Mindbody", 2019, ev_ebitda=None,
                              note="Vista took Mindbody private for ~$1.9B in 2019"),
        ComparableTransaction("Mindbody / ClassPass", 2021, ev_ebitda=None,
                              note="Mindbody acquired ClassPass in 2021; terms undisclosed"),
        ComparableTransaction("L Catterton + Meritech / EGYM", 2024, ev_ebitda=None,
                              note="~€180M invested at >€1B pre-money valuation"),
    ],

    risks=[
        "9.4x EV/Revenue on $800M is high for a mixed SaaS/hardware/marketplace business",
        "No EBITDA disclosed — investors are pricing on revenue growth, not current profitability",
        "Four different business models (SaaS, consumer marketplace, hardware, corporate wellness) create integration complexity",
        "ClassPass has faced criticism from small studio owners about rate fairness — scale may amplify this",
        "EGYM hardware business has different margin profile than Playlist's software/marketplace businesses",
        "Corporate wellness (Wellpass) is employer-dependent — recession-sensitive benefit",
        "Vista Equity Partners has been the controlling shareholder since 2019 — 7 years without exit",
    ],

    key_sources=[
        "playlist_egym_press_release", "playlist_egym_egym_page", "playlist_egym_athletech",
        "playlist_egym_munich_startup", "playlist_egym_kirkland", "playlist_zoominfo",
    ],
)


# =============================================================================
# ANALYSIS ENGINE
# =============================================================================

def print_separator(char="=", width=90):
    print(C["sep"] + char * width)


def print_header(title):
    print()
    print_separator()
    print(C["header"] + f"  {title}")
    print_separator()
    print()


def fmt(value, decimals=1, suffix="x", na="N/A"):
    if value is None:
        return C["na"] + na
    return C["multiple"] + f"{value:.{decimals}f}{suffix}"


def fmt_mm(value):
    if value is None:
        return C["na"] + "N/A"
    if abs(value) >= 1000:
        return C["money"] + f"${value / 1000:.1f}B"
    return C["money"] + f"${value:.0f}M"


def lbl(text):
    """Format a label (left-side key in key: value pairs)."""
    return C["label"] + text


def analyze_deal(deal: Deal):
    """Print a full analysis of a single deal."""
    print(f"  {lbl('Deal:')          :<30} {C['value']}{deal.name}")
    print(f"  {lbl('Acquirer:')      :<30} {C['value']}{deal.acquirer}")
    print(f"  {lbl('Target:')        :<30} {C['value']}{deal.target}")
    print(f"  {lbl('Sector:')        :<30} {C['value']}{deal.sector}")
    print(f"  {lbl('Announced:')     :<30} {C['value']}{deal.announced}")
    print(f"  {lbl('Status:')        :<30} {C['value']}{deal.closed}")
    print(f"  {lbl('Deal Value:')    :<30} {fmt_mm(deal.deal_value_mm)}")
    print(f"  {lbl('Enterprise Val:'):<30} {fmt_mm(deal.enterprise_value_mm)}")
    print(f"  {lbl('Consideration:') :<30} {C['value']}{deal.consideration}")
    print()
    print(f"  {lbl('Revenue:')       :<30} {fmt_mm(deal.revenue_mm)} {C['dim']}({deal.revenue_label})")
    if deal.alt_revenue_mm:
        print(f"  {lbl('Alt Revenue:')  :<30} {fmt_mm(deal.alt_revenue_mm)} {C['dim']}({deal.alt_revenue_label})")
    print()
    print(f"  {lbl('Reported EBITDA:'):<30} {fmt_mm(deal.reported_ebitda_mm)}")
    print(f"    {C['dim']}Source: {deal.ebitda_source_note}")
    print(f"    {C['warn']}WARNING: {deal.ebitda_definition_warning}")
    if deal.adjusted_ebitda_mm:
        print(f"  {lbl('Adjusted EBITDA:'):<30} {fmt_mm(deal.adjusted_ebitda_mm)} {C['caution']}(SHOWN FOR DISCLOSURE ONLY)")
        print(f"    {C['dim']}Note: {deal.adjusted_ebitda_note}")
    print()

    # Multiples
    print(C["sep"] + "  --- Entry Multiples (using REPORTED EBITDA only) ---")
    print(f"  {lbl('EV / Revenue:')         :<30} {fmt(deal.ev_revenue)}")
    if deal.ev_alt_revenue is not None:
        print(f"  {lbl('EV / Alt Revenue:')     :<30} {fmt(deal.ev_alt_revenue)} {C['dim']}(on {deal.alt_revenue_label})")
    print(f"  {lbl('EV / Reported EBITDA:') :<30} {fmt(deal.ev_reported_ebitda)}")
    if deal.reported_ebitda_margin is not None:
        print(f"  {lbl('Reported EBITDA Margin:'):<30} {fmt(deal.reported_ebitda_margin, 1, '%')}")
    print()


def compare_deals(deal_a: Deal, deal_b: Deal):
    """Run the full side-by-side comparison."""

    print_header("DEAL COMPARISON: OVERVIEW")
    for d in [deal_a, deal_b]:
        analyze_deal(d)
        print_separator("-")

    # --- Multiples Comparison ---
    print_header("ENTRY MULTIPLES COMPARISON (REPORTED EBITDA ONLY)")
    row_fmt = "  {:<30s} {:>30s} {:>30s}"
    print(C["header"] + row_fmt.format("Metric", deal_a.name.split("/")[0].strip(),
                         deal_b.name.split("/")[0].strip()))
    print(C["sep"] + row_fmt.format("-" * 30, "-" * 30, "-" * 30))
    print(row_fmt.format("Enterprise Value",
                         fmt_mm(deal_a.enterprise_value_mm),
                         fmt_mm(deal_b.enterprise_value_mm)))
    print(row_fmt.format("Revenue",
                         fmt_mm(deal_a.revenue_mm),
                         fmt_mm(deal_b.revenue_mm)))
    print(row_fmt.format("Reported EBITDA",
                         fmt_mm(deal_a.reported_ebitda_mm),
                         fmt_mm(deal_b.reported_ebitda_mm)))
    print(row_fmt.format("EV / Revenue",
                         fmt(deal_a.ev_revenue),
                         fmt(deal_b.ev_revenue)))
    print(row_fmt.format("EV / Reported EBITDA",
                         fmt(deal_a.ev_reported_ebitda),
                         fmt(deal_b.ev_reported_ebitda)))
    print(row_fmt.format("EBITDA Margin (reported)",
                         fmt(deal_a.reported_ebitda_margin, 1, "%"),
                         fmt(deal_b.reported_ebitda_margin, 1, "%") if deal_b.reported_ebitda_margin else C["na"] + "N/A"))
    print()

    # --- Key difference callout ---
    print(C["key_obs"] + "  KEY OBSERVATION:")
    if deal_a.ev_reported_ebitda and deal_b.ev_reported_ebitda:
        diff = deal_a.ev_reported_ebitda - deal_b.ev_reported_ebitda
        pct = (diff / deal_b.ev_reported_ebitda) * 100
        higher = deal_a.name if diff > 0 else deal_b.name
        print(C["key_obs"] + f"  {higher} trades at a {abs(pct):.0f}% {'premium' if diff > 0 else 'discount'} "
              f"on EV/Reported EBITDA.")
    elif deal_a.ev_reported_ebitda and not deal_b.ev_reported_ebitda:
        print(C["key_obs"] + f"  {deal_b.name} has NO disclosed EBITDA — direct multiple comparison impossible.")
        print(C["key_obs"] + f"  {deal_a.name} at {fmt(deal_a.ev_reported_ebitda)}{C['key_obs']} EV/Reported EBITDA is the only")
        print(C["key_obs"] + "  deal where this metric can be computed.")
    elif deal_b.ev_reported_ebitda and not deal_a.ev_reported_ebitda:
        print(C["key_obs"] + f"  {deal_a.name} has NO disclosed EBITDA — direct multiple comparison impossible.")
    print()

    # --- Revenue multiple comparison ---
    if deal_a.ev_revenue and deal_b.ev_revenue:
        rv_diff = deal_a.ev_revenue - deal_b.ev_revenue
        print(f"  On EV/Revenue: {C['value']}{deal_a.name.split('/')[0].strip()}{C['reset']} at {fmt(deal_a.ev_revenue)}{C['reset']} vs "
              f"{C['value']}{deal_b.name.split('+')[0].strip()}{C['reset']} at {fmt(deal_b.ev_revenue)}{C['reset']}.")
        if abs(rv_diff) > 0.5:
            higher_rv = deal_a.name if rv_diff > 0 else deal_b.name
            print(C["caution"] + f"  {higher_rv.split('/')[0].strip()} pays a materially higher revenue multiple.")
    print()

    # --- Synergies ---
    print_header("SYNERGY COMPARISON")
    for d in [deal_a, deal_b]:
        print(C["deal"] + f"  [{d.name}]")
        print(f"  {lbl('Cost Synergies:')   :<30} {fmt_mm(d.synergies.cost_synergies_mm)}")
        print(C["dim"] + f"    {d.synergies.cost_synergies_note}")
        print(f"  {lbl('Revenue Synergies:'):<30} {fmt_mm(d.synergies.revenue_synergies_mm)}")
        print(C["dim"] + f"    {d.synergies.revenue_synergies_note}")
        print(f"  {lbl('Rev. Synergy Inflation:'):<30} {C['caution']}{d.synergies.revenue_synergy_inflation}")
        print()

    print(C["key_obs"] + "  ASSESSMENT: Which deal uses more inflated revenue synergies?")
    print()
    print("  DOWNTOWN: The deal premium is almost entirely explained by unquantified")
    print("  strategic value — UMG buying indie distribution market share. At 19.4x")
    print("  reported EBITDA, this is priced like a music catalog (16-20x NPS) but")
    print("  operates like a low-margin services business (8-12x typical). The gap")
    print("  is the implied revenue synergy.")
    print()
    print("  PLAYLIST/EGYM: No EBITDA disclosed, so we can't assess the premium on")
    print("  earnings. At 9.4x EV/Revenue, the deal prices both companies as high-growth")
    print("  SaaS despite having hardware and marketplace components. Geographic")
    print("  cross-expansion (EGYM to US/Asia, Playlist to Europe) is plausible but")
    print("  unquantified. The $785M new equity injection suggests investors see")
    print("  growth that justifies the combined $7.5B valuation — but the math is")
    print("  opaque without profitability data.")
    print()
    print(C["value"] + "  BOTTOM LINE: " + C["reset"] + "Downtown's synergy inflation is more visible because we")
    print("  can see the EBITDA ($40M) and the price ($775M) don't add up without")
    print("  significant growth assumptions. Playlist/EGYM hides the question entirely")
    print("  by not disclosing EBITDA — which is arguably worse from a transparency")
    print("  standpoint, but means the synergy inflation can't be measured.")
    print()

    # --- Integration Costs ---
    print_header("INTEGRATION COSTS")
    for d in [deal_a, deal_b]:
        print(C["deal"] + f"  [{d.name}]")
        print(f"  {lbl('Disclosed:'):<30} {fmt_mm(d.integration_costs.total_mm)}")
        print(C["dim"] + f"  Notes: {d.integration_costs.note}")
        print()

    # --- Comparable Transactions ---
    print_header("COMPARABLE TRANSACTIONS")
    for d in [deal_a, deal_b]:
        print(C["deal"] + f"  [{d.name}]")
        for ct in d.comparable_transactions:
            ev_e = f"EV/EBITDA: {fmt(ct.ev_ebitda)}" if ct.ev_ebitda else ""
            ev_r = f"EV/Rev: {fmt(ct.ev_revenue)}" if ct.ev_revenue else ""
            mult_str = " | ".join(filter(None, [ev_r, ev_e, C["dim"] + ct.note]))
            print(f"    {C['value']}{ct.name} ({ct.year}): {mult_str}")
        print()

    # --- Risks ---
    print_header("KEY RISKS")
    for d in [deal_a, deal_b]:
        print(C["deal"] + f"  [{d.name}]")
        for i, r in enumerate(d.risks, 1):
            print(C["risk"] + f"    {i}. " + C["reset"] + r)
        print()

    # --- EBITDA Definition Deep Dive ---
    print_header("EBITDA DEFINITION ANALYSIS")
    print("  This analysis uses REPORTED (unadjusted) EBITDA only.")
    print("  Here is what we know about each deal's EBITDA definition:")
    print()
    for d in [deal_a, deal_b]:
        print(C["deal"] + f"  [{d.name}]")
        print(f"  {lbl('Reported EBITDA:'):<30} {fmt_mm(d.reported_ebitda_mm)}")
        print(C["dim"] + f"  Source: {d.ebitda_source_note}")
        print(C["warn"] + f"  Warning: {d.ebitda_definition_warning}")
        if d.adjusted_ebitda_mm:
            print(f"  {lbl('Adjusted EBITDA:'):<30} {fmt_mm(d.adjusted_ebitda_mm)} {C['caution']}(NOT USED IN ANALYSIS)")
            print(f"  {lbl('Gap (Adj - Reported):'):<30} {fmt_mm(d.adjusted_ebitda_mm - d.reported_ebitda_mm)}")
        print()

    print(C["value"] + "  CONCLUSION ON EBITDA COMPARABILITY:")
    print(C["reset"] + "  These two deals CANNOT be compared on EV/EBITDA because Playlist/EGYM")
    print("  discloses no EBITDA figure at all. Downtown's ~$40M is itself uncertain")
    print("  (sourced from anonymous parties, definition unknown). The only reliable")
    print("  comparison metric is EV/Revenue, where Downtown trades at 6.0x net revenue")
    print("  and Playlist/EGYM at 9.4x combined revenue. On gross revenue, Downtown")
    print("  is just 0.9x — but gross revenue is misleading due to agency accounting.")
    print()

    # --- Data Sources ---
    print_header("DATA SOURCES")
    all_source_keys = set(deal_a.key_sources + deal_b.key_sources)
    for key in sorted(all_source_keys):
        if key in SOURCES:
            s = SOURCES[key]
            print(C["value"] + f"  [{key}]")
            print(C["dim"] + f"    URL:  {s['url']}")
            print(C["dim"] + f"    Desc: {s['description']}")
            print(C["dim"] + f"    Date: {s['accessed']}")
            print()


# =============================================================================
# CHARTS
# =============================================================================

def plot_comparison(deal_a: Deal, deal_b: Deal):
    """Generate bar charts comparing the two deals."""
    if not HAS_MATPLOTLIB:
        print("matplotlib not installed — skipping charts.")
        return

    labels = [deal_a.name.split("/")[0].strip(), deal_b.name.split("+")[0].strip()]
    colors = ["#4C9BE8", "#E87B4C"]

    fig, axes = plt.subplots(2, 2, figsize=(13, 9))
    fig.suptitle("Deal Comparison: VMG/Downtown  vs.  Playlist+EGYM", fontsize=14, fontweight="bold")

    # --- Chart 1: Enterprise Value ---
    ax = axes[0, 0]
    evs = [deal_a.enterprise_value_mm / 1000, deal_b.enterprise_value_mm / 1000]
    bars = ax.bar(labels, evs, color=colors, width=0.5)
    ax.set_title("Enterprise Value ($B)")
    ax.set_ylabel("$ Billions")
    for bar, val in zip(bars, evs):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.05,
                f"${val:.1f}B", ha="center", va="bottom", fontweight="bold")
    ax.set_ylim(0, max(evs) * 1.2)

    # --- Chart 2: Revenue ---
    ax = axes[0, 1]
    revs = [deal_a.revenue_mm, deal_b.revenue_mm]
    rev_labels_short = ["Net Rev\n(Downtown)", "Combined Net Rev\n(Playlist+EGYM)"]
    bars = ax.bar(rev_labels_short, revs, color=colors, width=0.5)
    ax.set_title("Net Revenue ($M)")
    ax.set_ylabel("$ Millions")
    for bar, val in zip(bars, revs):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 5,
                f"${val:.0f}M", ha="center", va="bottom", fontweight="bold")
    ax.set_ylim(0, max(revs) * 1.25)

    # --- Chart 3: EV / Revenue Multiple ---
    ax = axes[1, 0]
    ev_revs = [deal_a.ev_revenue, deal_b.ev_revenue]
    bars = ax.bar(labels, ev_revs, color=colors, width=0.5)
    ax.set_title("EV / Net Revenue Multiple")
    ax.set_ylabel("Multiple (x)")
    ax.axhline(y=5, color="gray", linestyle="--", linewidth=0.8, label="5x reference")
    for bar, val in zip(bars, ev_revs):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.1,
                f"{val:.1f}x", ha="center", va="bottom", fontweight="bold")
    ax.set_ylim(0, max(ev_revs) * 1.25)
    ax.legend(fontsize=8)

    # --- Chart 4: EV / EBITDA (Downtown only; Playlist/EGYM N/A) ---
    ax = axes[1, 1]
    ebitda_vals = [
        deal_a.ev_reported_ebitda if deal_a.ev_reported_ebitda else 0,
        deal_b.ev_reported_ebitda if deal_b.ev_reported_ebitda else 0,
    ]
    bar_labels = [labels[0], f"{labels[1]}\n(N/A — not disclosed)"]
    bars = ax.bar(bar_labels, ebitda_vals, color=colors, width=0.5)
    ax.set_title("EV / Reported EBITDA Multiple")
    ax.set_ylabel("Multiple (x)")
    ax.axhline(y=10, color="gray", linestyle="--", linewidth=0.8, label="10x reference (services norm)")
    for bar, val, orig in zip(bars, ebitda_vals, [deal_a.ev_reported_ebitda, deal_b.ev_reported_ebitda]):
        label = f"{val:.1f}x" if orig else "N/A"
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.1,
                label, ha="center", va="bottom", fontweight="bold")
    ax.set_ylim(0, max(ebitda_vals + [12]) * 1.25)
    ax.legend(fontsize=8)

    plt.tight_layout()


def plot_comparable_transactions(deal_a: Deal, deal_b: Deal):
    """Bar chart of EV/EBITDA multiples across comparable transactions."""
    if not HAS_MATPLOTLIB:
        return

    # Collect comps that have an EV/EBITDA figure, tagging which deal they belong to
    comps_a = [(ct.name, ct.ev_ebitda, "#4C9BE8") for ct in deal_a.comparable_transactions if ct.ev_ebitda]
    comps_b = [(ct.name, ct.ev_ebitda, "#E87B4C") for ct in deal_b.comparable_transactions if ct.ev_ebitda]

    # Include the deals themselves as the highlighted bars
    deal_bars = [
        (f"{deal_a.name.split('/')[0].strip()}\n(THIS DEAL)", deal_a.ev_reported_ebitda, "#1A5C9E"),
    ]

    all_bars = comps_a + comps_b + deal_bars
    if not all_bars:
        return

    names = [b[0] for b in all_bars]
    values = [b[1] for b in all_bars]
    colors = [b[2] for b in all_bars]

    # Wrap long names for readability
    wrapped = []
    for n in names:
        words = n.split()
        mid = len(words) // 2
        wrapped.append(" ".join(words[:mid]) + "\n" + " ".join(words[mid:]) if len(words) > 3 else n)

    fig, ax = plt.subplots(figsize=(11, 6))
    bars = ax.bar(wrapped, values, color=colors, width=0.55, edgecolor="white", linewidth=0.8)

    ax.set_title("EV / EBITDA: Downtown Deal vs. Comparable Transactions", fontsize=13, fontweight="bold")
    ax.set_ylabel("EV / EBITDA Multiple (x)")
    ax.axhline(y=10, color="gray", linestyle="--", linewidth=1, label="~10x (services norm)")
    ax.axhline(y=16, color="#999", linestyle=":", linewidth=1, label="~16x (music catalog norm)")

    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.2,
                f"{val:.1f}x", ha="center", va="bottom", fontsize=9, fontweight="bold")

    legend_patches = [
        mpatches.Patch(color="#4C9BE8", label=f"Comps: {deal_a.name.split('/')[0].strip()}"),
        mpatches.Patch(color="#E87B4C", label=f"Comps: {deal_b.name.split('+')[0].strip()}"),
        mpatches.Patch(color="#1A5C9E", label="Downtown deal (actual)"),
    ]
    ax.legend(handles=legend_patches, fontsize=8)
    ax.set_ylim(0, max(values) * 1.25)
    plt.tight_layout()
    plt.show()


def plot_sensitivity_table(deal: Deal, ebitda_scenarios: list, ev_scenarios: list):
    """
    Render a colour-coded sensitivity table: rows = EBITDA assumptions,
    cols = EV assumptions, cells = implied EV/EBITDA multiple.
    """
    if not HAS_MATPLOTLIB:
        return

    data = np.array([[ev / eb for ev in ev_scenarios] for eb in ebitda_scenarios])

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.axis("off")

    col_labels = [f"EV ${ev}M" for ev in ev_scenarios]
    row_labels = [f"EBITDA ${eb}M" for eb in ebitda_scenarios]

    # Colour cells: green = below services norm (≤12x), yellow = elevated, red = high
    cell_colors = []
    for row in data:
        row_colors = []
        for val in row:
            if val <= 12:
                row_colors.append("#c6efce")   # green
            elif val <= 17:
                row_colors.append("#ffeb9c")   # yellow
            else:
                row_colors.append("#ffc7ce")   # red
        cell_colors.append(row_colors)

    cell_text = [[f"{val:.1f}x" for val in row] for row in data]

    tbl = ax.table(
        cellText=cell_text,
        rowLabels=row_labels,
        colLabels=col_labels,
        cellColours=cell_colors,
        loc="center",
        cellLoc="center",
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(10)
    tbl.scale(1.3, 1.6)

    # Bold the column/row corresponding to the deal's actual values
    actual_ev_idx = ev_scenarios.index(deal.enterprise_value_mm) if deal.enterprise_value_mm in ev_scenarios else None
    actual_eb_idx = ebitda_scenarios.index(deal.reported_ebitda_mm) if deal.reported_ebitda_mm in ebitda_scenarios else None
    if actual_ev_idx is not None and actual_eb_idx is not None:
        tbl[actual_eb_idx + 1, actual_ev_idx].set_text_props(fontweight="bold")

    ax.set_title(
        f"Sensitivity: {deal.name.split('/')[0].strip()} — EV/EBITDA at Varying Assumptions\n"
        "Green ≤ 12x (services norm) | Yellow 12–17x | Red > 17x",
        fontsize=11, fontweight="bold", pad=20,
    )

    # Add a note about actual values
    note = (f"Actual deal: EV = ${deal.enterprise_value_mm:.0f}M, "
            f"Reported EBITDA = ${deal.reported_ebitda_mm:.0f}M → "
            f"{deal.ev_reported_ebitda:.1f}x")
    fig.text(0.5, 0.02, note, ha="center", fontsize=9, style="italic", color="#333")

    plt.tight_layout()
    plt.show()


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    print()
    print(C["header"] + "=" * 90)
    print(C["header"] + "  FINANCIAL DEAL COMPARISON TOOL")
    print(C["header"] + "  VMG / Downtown Music  vs.  Playlist + EGYM")
    print(C["header"] + "  Using REPORTED EBITDA only (not adjusted)")
    print(C["header"] + "=" * 90)

    compare_deals(downtown, playlist_egym)
    plot_comparison(downtown, playlist_egym)
    plot_comparable_transactions(downtown, playlist_egym)
    plot_sensitivity_table(
        downtown,
        ebitda_scenarios=[20, 30, 40, 50, 60, 75],
        ev_scenarios=[600, 700, 775, 850, 950],
    )

    print_separator()
    print(C["header"] + "  END OF ANALYSIS")
    print_separator()